name: Deploy Jeykll site

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.0

    - run: bundle install
    - run: bundle exec jekyll build
    - name: Deploy via Rsync
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: --avzr --delete
        path: _site
        remote_path: /var/www/jekyll_site
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_port: ${{ secrets.REMOTE_PORT }}
        remote_key: ${{ secrets.REMOTE_KEY }}

