name: Deploy Jeykll site

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      uses: actions/jekyll-build-pages@v1
    - name: Deploy via Rsync
      uses: burnett01/rsync-deployments@7.0.2
      with:
        switches: -avzr --delete
        path: _site/
        remote_path: /var/www/jekyllsite
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_port: ${{ secrets.REMOTE_PORT }}
        remote_key: ${{ secrets.REMOTE_KEY }}

